apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SERVER_URL: "http://localhost:30011"
  ORIGIN: "http://localhost:30080,http://127.0.0.1:30080,http://localhost:5173,http://127.0.0.1:5173"
  DATABASE_URL: "mongodb://mongo:27017/chatapp"
  PEPPER_STRING: "murad"
  SESSION_SECRET: "your-session-secret-key-change-this"
  ADMIN_EMAIL: "admin@example.com"
  RESET_LOWER_LIMIT: "2024-01-01"
  AI_ASSISTANT_EMAIL: "hieu.ai@system"
  AI_ASSISTANT_FIRST_NAME: "Hieu"
  AI_ASSISTANT_LAST_NAME: "AI"
  AI_ASSISTANT_SYSTEM_PROMPT: "You are an upbeat Vietnamese-speaking AI copilot."
  AI_ASSISTANT_IMAGE: "/ai.jpg"
  AI_ASSISTANT_HISTORY_LIMIT: "50"
  LIVEKIT_URL: "wss://chat-app-d9qdpteh.livekit.cloud"
  AUTH_SERVICE_URL: "http://auth-user-service:4001"
  CHAT_SERVICE_URL: "http://chat-service:4002"
  MEDIA_SERVICE_URL: "http://media-ai-service:4003"
  VITE_SERVER_URL: "http://localhost:30011"
  NODE_ENV: "development"
  VITE_CLOUDINARY_CLOUD_NAME: "dqstqcaxd"
  VITE_CLOUDINARY_UPLOAD_PRESET: "unsigned_preset_1"
  VITE_CLOUDINARY_FOLDER: "uploads"
  VITE_MUSIC_1_NAME: "All I Want for Christmas Is You - Mariah Carey"
  VITE_MUSIC_1_URL: "/music/All I Want for Christmas Is You.mp3"
  VITE_MUSIC_2_NAME: "Vinh Quang Đang Chờ Ta"
  VITE_MUSIC_2_URL: "/music/Vinh Quang Đang Chờ Ta.mp3"
  VITE_MUSIC_3_NAME: "Bông Hoa Chẳng Tồn Tại - Huy Vạc"
  VITE_MUSIC_3_URL: "/music/Bông Hoa Chẳng Tồn Tại.mp3"
