apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  JWT_KEY: "florentino"
  GOOGLE_CLIENT_ID: "37387478146-048n48tqve48b09ejch4dh2dbenab45p.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_CALLBACK_URL: "http://localhost:30011/api/auth/google/callback"
  FACEBOOK_APP_ID: "your-facebook-app-id"
  FACEBOOK_APP_SECRET: "your-facebook-app-secret"
  FACEBOOK_CALLBACK_URL: "http://localhost:30011/api/auth/facebook/callback"
  GITHUB_CLIENT_ID: "Ov23liFD9p2JBMsLFINf"
  GITHUB_CLIENT_SECRET: "f32f88fe27649414ac7f4d16d2905bf681669973"
  GITHUB_CALLBACK_URL: "http://localhost:30011/api/auth/github/callback"
  GEMINI_API_KEY: "AIzaSyC3We0AoiRIVN1DRZJTOtmEFUgcO4OndjM"
  GEMINI_MODEL: "gemini-2.0-flash"
  LIVEKIT_API_KEY: "APIGq8KPzU6ooe6"
  LIVEKIT_API_SECRET: "vm6lFntPsLm1ZZQafqw2tccuDHFJ4b7CF8g8cPa1CqC"
