apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: chat-app
    env: cloud
  namespace: default
data:
  ALLOWED_ORIGINS: "https://vibechat.io.vn,http://136.110.57.178,http://34.142.152.144,http://34.87.94.25"
  VITE_SERVER_URL: "https://vibechat.io.vn"
  VITE_SOCKET_URL: "wss://vibechat.io.vn"


  VITE_CLOUDINARY_CLOUD_NAME: "dqstqcaxd"
  VITE_CLOUDINARY_UPLOAD_PRESET: "unsigned_preset_1"
  VITE_CLOUDINARY_FOLDER: "uploads"

  VITE_MUSIC_1_NAME: "All I Want for Christmas Is You - Mariah Carey"
  VITE_MUSIC_1_URL: "/music/All-I-Want-for-Christmas-Is-You.mp3"

  VITE_MUSIC_2_NAME: "Vinh Quang Dang Cho Ta (Seagames 33) - Soobin Hoang Son"
  VITE_MUSIC_2_URL: "/music/Vinh-Quang-Dang-Cho-Ta.mp3"

  VITE_MUSIC_3_NAME: "Bong Hoa Chang Ton Tai - Huy Vac"
  VITE_MUSIC_3_URL: "/music/Bong-Hoa-Chang-Ton-Tai.mp3"

  LIVEKIT_URL: "wss://chat-app-d9qdpteh.livekit.cloud"
  LIVEKIT_API_KEY: "APIGq8KPzU6ooe6"
  LIVEKIT_API_SECRET: "vm6lFntPsLm1ZZQafqw2tccuDHFJ4b7CF8g8cPa1CqC"

  AI_ASSISTANT_EMAIL: "hieu.ai@system"
  AI_ASSISTANT_FIRST_NAME: "Hieu"
  AI_ASSISTANT_LAST_NAME: "AI"
  AI_ASSISTANT_SYSTEM_PROMPT: "You are Vibe AI, an upbeat Vietnamese-speaking AI copilot built into VibeChat, the world-leading realtime messaging platform.
    Tone & Style:
    - Friendly, natural, concise.
    - Helpful but not verbose.
    - Conversational, not formal.
    - No sales pitch, no corporate tone.
    Response Rules:
    - Max 2–3 short sentences per reply.
    - If unclear, ask exactly one clarifying question.
    - No assumptions when data is missing.
    - Prefer bullet points when listing.
    - No emojis unless user explicitly asks.
    - If unsure, say: 'Chưa đủ thông tin để trả lời.'"
    
  AI_ASSISTANT_IMAGE: "/ai.jpg"
  AI_ASSISTANT_HISTORY_LIMIT: "50"

  GEMINI_API_KEY: "AIzaSyC5BUW6jRl7CCBIVpEYZvgh8xZRcjimvMA"
  GEMINI_MODEL: "gemini-2.0-flash"
