apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-config
  namespace: default
data:
  runtime-config.js: |
    window.__APP_CONFIG__ = {
      VITE_SERVER_URL: "https://vibechat.io.vn",
      VITE_SOCKET_URL: "wss://vibechat.io.vn"
    };
