apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: chat-app
    env: cloud
  namespace: default
type: Opaque
# Example, replace with real values or use Secret Manager integration
stringData:
  PORT: "3001"
  SERVER_URL: "http://api-gateway:3001"
  JWT_KEY: "florentino"
  ORIGIN: "http://your-cloud-domain.com,http://localhost:30080"
  DATABASE_URL: "mongodb://mongo:27017/chatapp"
  PEPPER_STRING: "murad"
  SESSION_SECRET: "your-session-secret-key-change-this"
  ADMIN_EMAIL: "admin@example.com"
  RESET_LOWER_LIMIT: "2024-01-01"
  GOOGLE_CLIENT_ID: "37387478146-048n48tqve48b09ejch4dh2dbenab45p.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_CALLBACK_URL: "http://api-gateway:3001/api/auth/google/callback"
  FACEBOOK_APP_ID: "your-facebook-app-id"
  FACEBOOK_APP_SECRET: "your-facebook-app-secret"
  FACEBOOK_CALLBACK_URL: "http://api-gateway:3001/api/auth/facebook/callback"
  GITHUB_CLIENT_ID: "Ov23liFD9p2JBMsLFINf"
  GITHUB_CLIENT_SECRET: "f32f88fe27649414ac7f4d16d2905bf681669973"
  GITHUB_CALLBACK_URL: "http://api-gateway:3001/api/auth/github/callback"
  NODE_ENV: "production"
  AUTH_SERVICE_URL: "http://auth-user-service:4001"
  CHAT_SERVICE_URL: "http://chat-service:4002"
  MEDIA_SERVICE_URL: "http://media-ai-service:4003"
