apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
  labels:
    app: chat-app
    env: cloud
type: Opaque
stringData:

  JWT_KEY: "florentino"
  DATABASE_URL: "mongodb+srv://hungvp711_db_user:tAMQ2iP7Mh5fBm3d@chat-app-1.lsrxwhx.mongodb.net/chatapp?retryWrites=true&w=majority&appName=chat-app-1"
  PEPPER_STRING: "murad"
  SESSION_SECRET: "your-session-secret-key-change-this"
  ADMIN_EMAIL: "admin@example.com"
  RESET_LOWER_LIMIT: "2024-01-01"
  NODE_ENV: "production"

  # API Gateway static IP
  SERVER_URL: "https://vibechat.io.vn"

  # FE static IP + gateway static IP
  ORIGIN: "http://136.110.57.178,https://vibechat.io.vn"

  GOOGLE_CLIENT_ID: "37387478146-048n48tqve48b09ejch4dh2dbenab45p.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_CALLBACK_URL: "https://vibechat.io.vn/api/auth/google/callback"

  FACEBOOK_APP_ID: "your-facebook-app-id"
  FACEBOOK_APP_SECRET: "your-facebook-app-secret"
  FACEBOOK_CALLBACK_URL: "http://34.142.152.144/api/auth/facebook/callback"

  GITHUB_CLIENT_ID: "Ov23liFD9p2JBMsLFINf"
  GITHUB_CLIENT_SECRET: "f32f88fe27649414ac7f4d16d2905bf681669973"
  GITHUB_CALLBACK_URL: "https://vibechat.io.vn/api/auth/github/callback"

  GEMINI_API_KEY: "AIzaSyDG4b6r6JTF86dvp7CiVMRpwASmAZGeaX4"
  GEMINI_MODEL: "gemini-2.0-flash"

  AUTH_SERVICE_URL: "http://auth-user-service:4001"
  CHAT_SERVICE_URL: "http://chat-service:4002"
  MEDIA_SERVICE_URL: "http://media-ai-service:4003"

  CHAT_SERVICE_PORT: "4002"
  MEDIA_SERVICE_PORT: "4003"

  #email verification
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "hieuhuy160105@gmail.com"
  SMTP_PASS: "fjfr kqzu gwal gsrn"
  SMTP_SECURE: "false"
  EMAIL_FROM: "Vibechat noreply@vibechat.com"

  REDIS_URL: "redis://default:Fg34NuHxrVeWMFzaFbcoQgZMy5VDoe8T@redis-12459.c334.asia-southeast2-1.gce.cloud.redislabs.com:12459"